permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: zinber
  email: luckyboyzb@gmail.com
  github: http://github.com/zinbers

# 站点信息
title: zinber的博客 
description: zinber的博客
url: http://google.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/@.png
favicon: /public/img/@.ico

# google analytics 设置
ga:
  id: UA-54775781-1
  url: zinbers.github.io

# disqus 设置
disqus:
  shortname: zinbers

# 主题设置，自动激活某个标签
active: 生活

# 首页除了最新文章外显示分类
cates: 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
