permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 刘惠民
  email: liu9662@gmail.com
  link: http://www.usct.edu.cn
  github: http://github.com/liuhuimin

# 站点信息
title: 刘惠民的博客 
description: 刘惠民的博客
url: http://www.usct.edu.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/@.png
favicon: /public/img/@.ico

# google analytics 设置
ga:
  id: UA-52177833-1
  url: liuhuimin.github.io

# disqus 设置
disqus:
  shortname: liuhuimin

# 主题设置，自动激活某个标签
active: 数据挖掘

# 首页除了最新文章外显示分类
cates: 

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
